### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by pakdev** [AArnott/Xunit.StaFact#36]
Using VS2019 16.3.7. Running any test with the `[WpfFact]`/`[StaFact]`/`[UIFact]` attribute causes:

```
[11/5/2019 7:27:06.971 AM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (32-bit Desktop .NET 4.0.30319.42000)
[11/5/2019 7:27:07.233 AM Warning] [xUnit.net 00:00:00.27] <AssemblyName>: Catastrophic error during deserialization: System.ArgumentException: Could not load type 'Xunit.Sdk.UITestCase, Xunit.StaFact' from serialization value 'Xunit.Sdk.UITestCase, Xunit.StaFact:VGVzdE1ld...(elided)'
Parameter name: serializedValue
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 35
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 84
   at Xunit.DefaultTestCaseBulkDeserializer.<BulkDeserialize>b__2_0(String serialization) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Descriptor\DefaultTestCaseBulkDeserializer.cs:line 22
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunit.DefaultTestCaseBulkDeserializer.BulkDeserialize(List`1 serializations) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Descriptor\DefaultTestCaseBulkDeserializer.cs:line 22
   at Xunit.Xunit2.BulkDeserialize(List`1 serializations) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 74
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 562
```

**Comment by AArnott** [comment]
No repro for me. Please include more of a repro case if this still happens for you.

**Comment by campersau** [comment]
I think the issue is related to the `appDomain="denied"` setting which breaks assembly loading during test discovery and binding redirects.
You can add a custom `XunitTestFramework` which provides a custom assembly resolver to resolve binding redirects and loading assemblies when tests are discovered inside of Visual Studio.

```csharp
[assembly: TestFramework("XUnitTestProject.MyTestFramework", "XUnitTestProject")]

namespace XUnitTestProject
{
    public class MyTestFramework : XunitTestFramework
    {
        public MyTestFramework(IMessageSink messageSink)
            : base(messageSink)
        {
            DisposalTracker.Add(new AssemblyResolver());
        }
    }

    internal class AssemblyResolver : IDisposable
    {
        public AssemblyResolver()
        {
            AppDomain.CurrentDomain.AssemblyResolve += AssemblyResolve;
        }

        public void Dispose()
        {
            AppDomain.CurrentDomain.AssemblyResolve -= AssemblyResolve;
        }

        private Assembly AssemblyResolve(object sender, ResolveEventArgs args)
        {
            var assemblyName = new AssemblyName(args.Name);
            foreach (var filePath in LookupFiles(assemblyName.Name))
            {
                if (File.Exists(filePath))
                {
                    return Assembly.LoadFrom(filePath);
                }
            }
            return null;
        }

        private IEnumerable<string> LookupFiles(string name)
        {
            var fileName = name + ".dll";

            // resolve assemblies during test execution
            yield return Path.Combine(Environment.CurrentDirectory, fileName);
            // resolve assemblies during Visual Studio test discovery
            yield return Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), fileName);
        }
    }
}
```
